stages:
  - test
  - deploy
  
default:
  image: python:3.9

  before_script:
    - python --version
    - pip --version
    - echo "$TRANSPILER_PATH"
    

run_tests:
  stage: test

  script:
    - cd ./$TRANSPILER_PATH
    - pip install .[testing,stacks]
    - python tests/run_tests.py

  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH


run_linting:
  stage: test

  script:
    - pip install flake8
    - flake8 $TRANSPILER_PATH

  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
    
    
pages:
  stage: deploy
  
  script:
    - echo "Deploying documentation to $CI_PAGES_URL"

    - pip install pdoc3    
    - pip install ./$TRANSPILER_PATH/.
    - pdoc --html ./$TRANSPILER_PATH/qml_transpiler --output-dir public
    - mv public/qml_transpiler/* public/

  artifacts:
    paths:
      - public
#    expire_in: 20 minutes

  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH