stages:
  - test
  - deploy
  - documentation

default:
  image: python:3.9

  before_script:
    - python --version
    - pip --version
    - echo "$TRANSPILER_PATH"

run_tests:
  stage: test

  script:
    - cd ./$TRANSPILER_PATH
    - pip install .[testing,stacks]
    - python tests/run_tests.py

  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH

run_linting:
  stage: test

  script:
    - pip install flake8
    - flake8 $TRANSPILER_PATH

  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH

pages:
  stage: documentation
  script:
    - apt update
    - apt -y install gcc python3-dev pandoc python3-psutil
    - pip3 install .
    - pip3 install -r ./docs/requirements.txt
    - python3 -m sphinx -b html ./docs/source public
  artifacts:
    paths:
      - public
  # rules:
  #   - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
