stages:
  - test
  - documentation

default:
  image: python:3.10
  before_script:
    - python --version
    - pip --version
    - echo "$TRANSPILER_PATH"

tests:
  stage: test
  script:
    - cd ./$TRANSPILER_PATH
    - pip install --upgrade pip
    - pip install .[all]
    - python tests/run_tests.py

#  rules:
#    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH

test_old_qiskit_version:
  stage: test
  script:
    - cd ./$TRANSPILER_PATH
    - pip install --upgrade pip
    - pip install .[all]

    - pip install qiskit==1.0.2
    - pip install qiskit-aer==0.13.3
    - pip install qiskit-ibm-runtime==0.22.0

    - pip install pytket==1.31.0
    - pip install pytket-qiskit==0.51.0

    - python tests/run_tests.py

#  rules:
#    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH

linting:
  stage: test
  script:
    - pip install flake8
    - flake8 $TRANSPILER_PATH
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH

pages:
  stage: documentation
  script:
    - echo "Deploying GitLab documentation"
    - pip install pdoc3
    - pip install ./$TRANSPILER_PATH/.
    - pdoc --html ./$TRANSPILER_PATH/rivet_transpiler --output-dir public_gitlab
    - mv public_gitlab/rivet_transpiler/* public_gitlab/
    - echo "Deployed GitLab documentation to $CI_PAGES_URL"
  artifacts:
    paths:
      - public_gitlab
    # expire_in: 20 minutes
  publish: public_gitlab
  rules:
    - if: $CI_COMMIT_REF_NAME == "develop"

github_documentation:
  stage: documentation
  script:
    - echo "Deploying GitHub documentation"
    - apt update
    - apt -y install gcc python3-dev pandoc python3-psutil
    - pip3 install ./$TRANSPILER_PATH/.
    - pip3 install -r ./$TRANSPILER_PATH/docs/requirements.txt
    - python3 -m sphinx -b html ./$TRANSPILER_PATH/docs/source public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
